language: php
python:
    "3.6"
install:
     "pip install -r requirements.txt" 
script: 
     - "python test_user.py"
     -  "python test_shoppinglist.py"
     - "coverage run test_user.py"
     - "coverage run test_shoppinglist.py"
after_success: coveralls