language: php
python:
    "3.6"
install:
     "pip install -r requirements.txt" 
script: 
     - "python tests/test_user.py"
     -  "python tests/test_shoppinglist.py"
     - "coverage run tests/test_user.py"
     - "coverage run tests/test_shoppinglist.py"
after_success: coveralls